"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INITIAL_VAR = "__initial";
exports.REQUIRE_FUNC_NAME = "loadModule";
var NavigateContext_1 = require("./lib/NavigateContext");
exports.NavigateContext = NavigateContext_1.default;
var SeansStatusContext_1 = require("./lib/SeansStatusContext");
exports.SeansStatusContext = SeansStatusContext_1.default;
var NetworkStatusContext_1 = require("./lib/NetworkStatusContext");
exports.NetworkStatusContext = NetworkStatusContext_1.default;
var HistoryContext_1 = require("./lib/HistoryContext");
exports.HistoryContext = HistoryContext_1.default;
var StyledContext_1 = require("./lib/StyledContext");
exports.StyledContext = StyledContext_1.default;
var Link_1 = require("./lib/Link");
exports.Link = Link_1.default;
var Styled_1 = require("./lib/Styled");
exports.Styled = Styled_1.default;
var RemoteMessageType;
(function (RemoteMessageType) {
    RemoteMessageType["FrameControllerData"] = "frame-controller-data";
    RemoteMessageType["NewPage"] = "new-page";
    RemoteMessageType["Initialize"] = "initialize";
    RemoteMessageType["FrameControllerDispatch"] = "frame-controller-dispatch";
    RemoteMessageType["Navigate"] = "navigate";
    RemoteMessageType["Error"] = "error";
})(RemoteMessageType = exports.RemoteMessageType || (exports.RemoteMessageType = {}));
